<?php

namespace App\Filament\App\Resources\ClassroomResource\Pages;

use App\Filament\App\Resources\ClassroomResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateClassroom extends CreateRecord
{
    protected static string $resource = ClassroomResource::class;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getCreatedNotification(): ?\Filament\Notifications\Notification
    {
        $record = $this->record;

        $auth = auth()->user();

        $notification = \Filament\Notifications\Notification::make()
            ->success()
            ->icon('heroicon-o-finger-print')
            ->title('Classroom Resource Created')
            ->body("New Classroom {$record->name} Generated by {$auth->name}!")
            ->actions([\Filament\Notifications\Actions\Action::make('View')->url(ClassroomResource::getUrl('edit', ['record' => $record]))])
            ->sendToDatabase([$auth]);


        return $notification;
    }
}
