<?php

namespace App\Filament\App\Resources\CategoryResource\Pages;

use App\Filament\App\Resources\CategoryResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateCategory extends CreateRecord
{
    protected static string $resource = CategoryResource::class;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getCreatedNotification(): ?\Filament\Notifications\Notification
    {
        $record = $this->record;

        $auth = auth()->user();

        $notification = \Filament\Notifications\Notification::make()
            ->success()
            ->icon('heroicon-o-rectangle-group')
            ->title('Category Resource Created')
            ->body("New Category {$record->name} Generated by {$auth->name}!")
            ->actions([\Filament\Notifications\Actions\Action::make('View')->url(CategoryResource::getUrl('edit', ['record' => $record]))])
            ->sendToDatabase([$auth]);


        return $notification;
    }
}
