<?php

namespace App\Filament\App\Resources\BrandsResource\Pages;

use App\Filament\App\Resources\BrandsResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateBrands extends CreateRecord
{
    protected static string $resource = BrandsResource::class;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getCreatedNotification(): ?\Filament\Notifications\Notification
    {
        $record = $this->record;

        $auth = auth()->user();

        $notification = \Filament\Notifications\Notification::make()
            ->success()
            ->icon('heroicon-o-rectangle-group')
            ->title('Brand Resource Created')
            ->body("New Brand {$record->name} Generated by {$auth->name}!")
            ->actions([\Filament\Notifications\Actions\Action::make('View')->url(BrandsResource::getUrl('edit', ['record' => $record]))])
            ->sendToDatabase([$auth]);


        return $notification;
    }
}
