<?php

namespace App\Filament\App\Resources\SectionResource\Pages;

use App\Filament\App\Resources\SectionResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateSection extends CreateRecord
{
    protected static string $resource = SectionResource::class;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getCreatedNotification(): ?\Filament\Notifications\Notification
    {
        $record = $this->record;

        $auth = auth()->user();

        $notification = \Filament\Notifications\Notification::make()
            ->success()
            ->icon('heroicon-o-rectangle-group')
            ->title('Section Resource Created')
            ->body("New Section {$record->name} Generated by {$auth->name}!")
            ->actions([\Filament\Notifications\Actions\Action::make('View')->url(SectionResource::getUrl('edit', ['record' => $record]))])
            ->sendToDatabase([$auth]);


        return $notification;
    }
}
